databases:
  - name: rails_apps_db_instance
    databaseName: rails_apps_db_instance
    user: rails_apps
    plan: free

services:
  - type: web
    name: blog
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails_apps_db_instance
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default